return {
  -- {
  --   "CopilotC-Nvim/CopilotChat.nvim",
  --   opts = {
  --     debug = false,
  --     show_help = "yes",
  --     prompts = {
  --       Explain = "Explain how it works.",
  --       Review = "Review the following code and provide concise suggestions.",
  --       Tests = "Briefly explain how the selected code works, then generate unit tests.",
  --       Refactor = "Refactor the code to improve clarity and readability.",
  --     },
  --     disable_extra_info = "no", -- Disable extra information (e.g: system prompt) in the response.
  --   },
  --   build = function()
  --     vim.notify("Please update the remote plugins by running ':UpdateRemotePlugins', then restart Neovim.")
  --   end,
  --   event = "VeryLazy",
  --   keys = {
  --     { "<leader>cce", "<cmd>CopilotChatExplain<cr>", desc = "CopilotChat - Explain code" },
  --     { "<leader>cct", "<cmd>CopilotChatTests<cr>", desc = "CopilotChat - Generate tests" },
  --     { "<leader>ccr", "<cmd>CopilotChatReview<cr>", desc = "CopilotChat - Review code" },
  --     { "<leader>ccR", "<cmd>CopilotChatRefactor<cr>", desc = "CopilotChat - Refactor code" },
  --     {
  --       "<leader>ccv",
  --       ":CopilotChatVisual",
  --       mode = "x",
  --       desc = "CopilotChat - Open in vertical split",
  --     },
  --     {
  --       "<leader>ccx",
  --       ":CopilotChatInPlace<cr>",
  --       mode = "x",
  --       desc = "CopilotChat - Run in-place code",
  --     },
  --   },
  -- },
}
